### ISSUE TITLE
[Texture Pack request] Fluent Design Texture Pack

### ISSUE THREAD

**Issue by akhilesh-balaji** [UnofficialSamHub/MeadowLand#40]
**Describe the pack you'd like**
I'd like a Texture pack with fluent design elements such as gradients. This pack wouldn't have those pixel sprites, just smooth corners and edges.

**Describe alternatives you've considered**
I've considered making a pack myself for this.

**Additional context**
By fluent design, I mean the Fluent Design guidelines by Microsoft that Windows 10 is being updated with. Here are some examples of fluent design icons:
![image](https://user-images.githubusercontent.com/69246693/99206726-2adab300-27e2-11eb-97a5-e9fcdc575499.png)
![image](https://user-images.githubusercontent.com/69246693/99206755-38903880-27e2-11eb-9f2f-8ffa617443cc.png)
![image](https://user-images.githubusercontent.com/69246693/99206801-4cd43580-27e2-11eb-8503-45b5c87349d7.png)
![image](https://user-images.githubusercontent.com/69246693/99206833-5f4e6f00-27e2-11eb-958f-5e26bf681377.png)

**Comment by PotNoodl** [comment]
this is simply not possible unfortunately

the way the system is designed is that it uses a sprite sheet, you can't change the spritesheet's size meaning you are stuck with the pixel art asthetic
