### ISSUE TITLE
SVG sprite sheet

### ISSUE THREAD

**Issue by akhilesh-balaji** [UnofficialSamHub/MeadowLand#41]
The current sprite sheet is in a `.png (Portable Network Graphics)` format, which is really hard to edit. It would be nice if a `.svg (Scalable Vector Graphics)` version of this was available for easy editing. This could then be exported as a `.png`.

This did not fit into any of the existing issue templates, so I opened a blank one.

**Comment by PotNoodl** [comment]
you understand that the reason it is a PNG is because it is pixel art, you can't have a pixel art image be an SVG
with the current system in place this is simply not possible

**Comment by PotNoodl** [comment]
may i also add that editing a png is not that hard
also this github repo is purely community content, we have no say in the development of the actual program
